In [1]:
import pandas as pd 
import numpy as np
house_sales = "Resources/Perth_Housing_Prices.csv"
sales_df = pd.read_csv(house_sales)
sales_df.set_index('ADDRESS', inplace=True)
sales_df.head()

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
sales_df['GARAGE'] = sales_df['GARAGE'].fillna(0)

In [3]:
sales_df['SUBURB'].value_counts()

Bertram            231
Iluka              212
Bennett Springs    211
Mindarie           209
Carramar           208
                  ...
Northbridge         11
Keysbrook            9
O'Connor             8
Neerabup             8
Hope Valley          6
Name: SUBURB, Length: 314, dtype: int64

In [4]:
sales_df.columns

Index(['SUBURB', 'PRICE', 'BEDROOMS', 'BATHROOMS', 'GARAGE', 'LAND_AREA',
       'FLOOR_AREA', 'BUILD_YEAR', 'CBD_DIST', 'NEAREST_STN',
       'NEAREST_STN_DIST', 'DATE_SOLD', 'POSTCODE', 'LATITUDE', 'LONGITUDE',
       'NEAREST_SCH', 'NEAREST_SCH_DIST', 'NEAREST_SCH_RANK'],
      dtype='object')

In [5]:
# column names for recombining dataframe
columns = ['SUBURB', 'PRICE', 'BEDROOMS', 'BATHROOMS', 'GARAGE', 'LAND_AREA',
       'FLOOR_AREA', 'BUILD_YEAR', 'CBD_DIST', 'NEAREST_STN',
       'NEAREST_STN_DIST', 'DATE_SOLD', 'POSTCODE', 'LATITUDE', 'LONGITUDE',
       'NEAREST_SCH', 'NEAREST_SCH_DIST', 'NEAREST_SCH_RANK', 'Prediction']

In [6]:
# create empty dataframe for recombining into
combined_df = pd.DataFrame(columns=columns)
combined_df

Empty DataFrame
Columns: [SUBURB, PRICE, BEDROOMS, BATHROOMS, GARAGE, LAND_AREA, FLOOR_AREA, BUILD_YEAR, CBD_DIST, NEAREST_STN, NEAREST_STN_DIST, DATE_SOLD, POSTCODE, LATITUDE, LONGITUDE, NEAREST_SCH, NEAREST_SCH_DIST, NEAREST_SCH_RANK, Prediction]
Index: []

In [7]:
pred_house_sell = {}
temp = {}

# loop on every suburb
for SUBURB in sales_df['SUBURB'].unique():
    # slice
    sales_slice = sales_df[sales_df['SUBURB'] == SUBURB]
    df = sales_slice.copy()

    # set X and y
    y = sales_slice['PRICE']
    X = sales_slice.drop(['SUBURB', 'PRICE', 'NEAREST_STN', 'DATE_SOLD', 'POSTCODE', 'LATITUDE', 'LONGITUDE', 
                          'NEAREST_SCH', 'NEAREST_SCH_RANK'], axis=1)
    
    # scale the data
    X_scaled = StandardScaler().fit_transform(X)

    # train, test, split
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y)

    #building linear regression model on training data
    model1= LinearRegression().fit(X_train, y_train)
    pred_house_sell[SUBURB] = model1.predict(X_test)
    
    # make prediction and add it to the sliced dataframe
    prediction = model1.predict(X_scaled)
    df['Prediction'] = prediction
   
    # rebuild full dataframe
    combined_df = pd.concat([combined_df, df], ignore_index=False)

    # print r2 score
    print('Accuracy Score:', r2_score(y_test, pred_house_sell[SUBURB]))  

    # build dictionary with all r2 scores
    temp[SUBURB] = r2_score(y_test, pred_house_sell[SUBURB])

# convert dictionary to dataframe
temp = pd.DataFrame.from_dict(temp, orient ='index').reset_index()

Accuracy Score: 0.5672405291913516
Accuracy Score: 0.3592606303214878
Accuracy Score: 0.47459853205923086
Accuracy Score: 0.5290514071087253
Accuracy Score: 0.556061589083837
Accuracy Score: 0.10667587595173067
Accuracy Score: -0.04862023772396684
Accuracy Score: 0.1322117276564223
Accuracy Score: 0.6991573696000191
Accuracy Score: 0.38957857475119106
Accuracy Score: 0.2876067951621011
Accuracy Score: 0.6408330531434461
Accuracy Score: 0.6075093962921381
Accuracy Score: 0.1420032326365941
Accuracy Score: 0.3331549522509941
Accuracy Score: -0.4310825264255309
Accuracy Score: -0.21476804914980807
Accuracy Score: 0.04707304994395545
Accuracy Score: 0.40706608143949397
Accuracy Score: 0.6324681356897932
Accuracy Score: 0.6320158852751281
Accuracy Score: 0.5089670298231548
Accuracy Score: 0.5217195050899655
Accuracy Score: 0.7621752570101984
Accuracy Score: 0.6445096230173466
Accuracy Score: 0.37527093779506293
Accuracy Score: 0.22256641260547094
Accuracy Score: -1.5928570833227247
Accuracy Score: 0.2527199539556707
Accuracy Score: 0.5565536802702706
Accuracy Score: 0.712273802604733
Accuracy Score: 0.5705344866921609
Accuracy Score: 0.500290246369872
Accuracy Score: 0.6419251108844549
Accuracy Score: 0.19728612174599935
Accuracy Score: 0.5515888258352355
Accuracy Score: 0.5286069238790225
Accuracy Score: 0.4489805539878454
Accuracy Score: 0.47083966678865297
Accuracy Score: 0.29945250886695296
Accuracy Score: 0.16353245231704705
Accuracy Score: 0.6021997792731215
Accuracy Score: 0.7882680103395727
Accuracy Score: 0.22457832974612824
Accuracy Score: -18.76000790359038
Accuracy Score: 0.2232485719961338
Accuracy Score: -0.6250604644819786
Accuracy Score: 0.7140834406966228
Accuracy Score: -1.303921953125402
Accuracy Score: 0.20327886853293053
Accuracy Score: 0.5515089914495444
Accuracy Score: 0.5228853376949026
Accuracy Score: -0.5170795524318221
Accuracy Score: 0.37894058106625106
Accuracy Score: 0.47116648621458723
Accuracy Score: -2.8069750110082805
Accuracy Score: -0.11448748050871349
Accuracy Score: 0.3063359619483247
Accuracy Score: 0.2343510004697117
Accuracy Score: 0.6985877984916786
Accuracy Score: -2.715055091286506
Accuracy Score: -9.905364964547996
Accuracy Score: 0.8692428534282309
Accuracy Score: 0.7632714211616122
Accuracy Score: -0.07246351234611348
Accuracy Score: 0.6169276199997936
Accuracy Score: 0.5494153109031192
Accuracy Score: 0.6759841037828389
Accuracy Score: -0.48451040218327157
Accuracy Score: -0.7737735752918518
Accuracy Score: -1.3820747293441924
Accuracy Score: -0.21410465352028574
Accuracy Score: -0.7693024621121107
Accuracy Score: 0.28528014084817843
Accuracy Score: 0.6248096370638934
Accuracy Score: 0.4364149909429984
Accuracy Score: -0.12822343044346995
Accuracy Score: 0.7053400173775345
Accuracy Score: 0.05345053520827203
Accuracy Score: 0.5601972632628734
Accuracy Score: 0.5619593072767414
Accuracy Score: 0.254774871485567
Accuracy Score: 0.4614449279184434
Accuracy Score: -0.6977258201048417
Accuracy Score: 0.4458776334686192
Accuracy Score: 0.22920034574073977
Accuracy Score: 0.7053109396624545
Accuracy Score: 0.06416512863847623
Accuracy Score: 0.49092578778326645
Accuracy Score: 0.741190188725722
Accuracy Score: -0.413427344104794
Accuracy Score: 0.7213607307484924
Accuracy Score: 0.3197251692766534
Accuracy Score: 0.5131233438746359
Accuracy Score: 0.46590879267585616
Accuracy Score: -0.606666055103241
Accuracy Score: 0.797489491189064
Accuracy Score: 0.4331149077613813
Accuracy Score: 0.2776712831649475
Accuracy Score: 0.14463540228109528
Accuracy Score: 0.7364204945463723
Accuracy Score: 0.26703398861301697
Accuracy Score: 0.7749278364706801
Accuracy Score: 0.0687399728777498
Accuracy Score: 0.4585558855942705
Accuracy Score: 0.6525121923089028
Accuracy Score: 0.5707367718730085
Accuracy Score: 0.6856627656194838
Accuracy Score: 0.677236535268145
Accuracy Score: 0.5230906428517903
Accuracy Score: 0.09579645928569458
Accuracy Score: 0.8143330819054593
Accuracy Score: -0.2501979784782573
Accuracy Score: -1.0059997109826941
Accuracy Score: 0.40584357466711585
Accuracy Score: 0.3255610008506531
Accuracy Score: 0.6801768799945948
Accuracy Score: 0.38967565146079186
Accuracy Score: 0.017512826900721423
Accuracy Score: 0.6466799732520233
Accuracy Score: 0.7328463032529733
Accuracy Score: 0.22776028339025134
Accuracy Score: -1.1714782694299246
Accuracy Score: 0.1725130747096879
Accuracy Score: 0.09297758079103013
Accuracy Score: 0.4491912604656736
Accuracy Score: 0.4799100578638461
Accuracy Score: 0.11962879472717936
Accuracy Score: 0.5622221799488576
Accuracy Score: -1.4535546486103708
Accuracy Score: 0.46423603791600443
Accuracy Score: -0.01862679227676911
Accuracy Score: 0.678901348384964
Accuracy Score: 0.5087581641627735
Accuracy Score: -0.45765692045737927
Accuracy Score: 0.18286470454008874
Accuracy Score: -0.35499261566395446
Accuracy Score: 0.757385125571961
Accuracy Score: 0.40602309688625626
Accuracy Score: 0.7362469559667744
Accuracy Score: 0.39877834468294526
Accuracy Score: 0.3515279081243572
Accuracy Score: -0.24900864321734528
Accuracy Score: 0.5628457423784339
Accuracy Score: 0.6590292435479879
Accuracy Score: 0.8183603216181623
Accuracy Score: 0.527055311241748
Accuracy Score: 0.658707480291181
Accuracy Score: -7.626214678418288
Accuracy Score: 0.45646976031632747
Accuracy Score: 0.3324566069083822
Accuracy Score: 0.5302225493508187
Accuracy Score: 0.5444871817634576
Accuracy Score: -1.6053939340355945
Accuracy Score: 0.9500151420040974
Accuracy Score: 0.3710390620822063
Accuracy Score: 0.5959357726962798
Accuracy Score: -1.0207832149803795
Accuracy Score: 0.8247223383305011
Accuracy Score: 0.6289384318953108
Accuracy Score: 0.5720278005911452
Accuracy Score: 0.6177448462096471
Accuracy Score: 0.2673313794976645
Accuracy Score: 0.8470296490160281
Accuracy Score: 0.8055076795600834
Accuracy Score: -3.3766570347041904
Accuracy Score: 0.6643439252301473
Accuracy Score: 0.7084761173984726
Accuracy Score: 0.5877455225118422
Accuracy Score: 0.7028386898819485
Accuracy Score: -2.2247030077432455
Accuracy Score: -0.8446463121607406
Accuracy Score: 0.30632325559899043
Accuracy Score: -0.2037486535377786
Accuracy Score: 0.6612256441104175
Accuracy Score: 0.45054846382070424
Accuracy Score: 0.17218204664646075
Accuracy Score: 0.38087803002660303
Accuracy Score: 0.5477805839645433
Accuracy Score: 0.6560522791948775
Accuracy Score: -0.8867516516028211
Accuracy Score: 0.49000645983317304
Accuracy Score: 0.07071598116120559
Accuracy Score: 0.5934867853777359
Accuracy Score: -0.04563279245187335
Accuracy Score: 0.650802559609094
Accuracy Score: -60.169560980574495
Accuracy Score: 0.7299668174893732
Accuracy Score: 0.5815118090297565
Accuracy Score: -1.6062724299024298
Accuracy Score: 0.2968273686240057
Accuracy Score: 0.7618598815694514
Accuracy Score: 0.023642875056736345
Accuracy Score: 0.6226488595367334
Accuracy Score: -10.016144790884795
Accuracy Score: 0.79998721414347
Accuracy Score: 0.8531793840331389
Accuracy Score: 0.5447303342476023
Accuracy Score: 0.09862462260290583
Accuracy Score: 0.5888888593345246
Accuracy Score: -0.08188161430232999
Accuracy Score: 0.7817148523965842
Accuracy Score: -0.1314732143050279
Accuracy Score: 0.6908888235323671
Accuracy Score: 0.5005890359204754
Accuracy Score: 0.5670138373592502
Accuracy Score: -0.870222975439491
Accuracy Score: 0.7834898479317696
Accuracy Score: 0.6288763725392605
Accuracy Score: 0.3119844179954092
Accuracy Score: 0.7705335608749537
Accuracy Score: 0.37542925783028136
Accuracy Score: 0.4472917546742522
Accuracy Score: 0.5265339200066161
Accuracy Score: 0.4895746774896741
Accuracy Score: 0.35402955380759393
Accuracy Score: 0.05799979852585835
Accuracy Score: -1.2243648102113247
Accuracy Score: 0.7759870382699067
Accuracy Score: 0.4709413722038144
Accuracy Score: 0.3639748195728538
Accuracy Score: 0.42750173390336244
Accuracy Score: -3.4266226891745406
Accuracy Score: 0.8102328846050293
Accuracy Score: 0.4767138930847419
Accuracy Score: 0.5577147303282124
Accuracy Score: 0.624071534361751
Accuracy Score: 0.5368329297692229
Accuracy Score: 0.403012923959444
Accuracy Score: 0.24628070017278225
Accuracy Score: -9.858042443172202
Accuracy Score: 0.5116919228957046
Accuracy Score: 0.635095600375235
Accuracy Score: 0.6208786296604432
Accuracy Score: 0.16125168929590805
Accuracy Score: 0.6496676509258565
Accuracy Score: 0.5773548357934186
Accuracy Score: 0.7084723665987047
Accuracy Score: 0.6413940429000495
Accuracy Score: 0.8072970884646637
Accuracy Score: 0.29675212967461073
Accuracy Score: 0.37820890926335604
Accuracy Score: 0.5010075221991113
Accuracy Score: 0.5630050122000747
Accuracy Score: 0.7054208011775775
Accuracy Score: 0.47865813841867966
Accuracy Score: 0.6655908828055082
Accuracy Score: 0.3546859904179186
Accuracy Score: 0.3309581163379385
Accuracy Score: -2.25797225329351
Accuracy Score: 0.4984941655789735
Accuracy Score: 0.20855487023342634
Accuracy Score: 0.3320509983089708
Accuracy Score: 0.4752801442696786
Accuracy Score: 0.3480612442228551
Accuracy Score: 0.6505941367041801
Accuracy Score: -1.9162126587550676
Accuracy Score: 0.6498893868206866
Accuracy Score: 0.5865648187666606
Accuracy Score: 0.1718230603692651
Accuracy Score: 0.17162879659915686
Accuracy Score: 0.4054499341206458
Accuracy Score: 0.3375831227045589
Accuracy Score: 0.46920496036304704
Accuracy Score: 0.4850547339205581
Accuracy Score: 0.6917030310029365
Accuracy Score: 0.26844852167799704
Accuracy Score: 0.5113176110385711
Accuracy Score: 0.049164691860782206
Accuracy Score: 0.0448926137910205
Accuracy Score: 0.482078021589473
Accuracy Score: 0.18113980021926468
Accuracy Score: 0.4683874667534902
Accuracy Score: 0.8151255075896308
Accuracy Score: -6.426564720797348
Accuracy Score: 0.270235688507908
Accuracy Score: -0.3118327601270743
Accuracy Score: 0.44009669397930795
Accuracy Score: 0.4942202039381073
Accuracy Score: 0.2832273138222623
Accuracy Score: 0.6956918363316117
Accuracy Score: 0.4699429656404249
Accuracy Score: 0.5323165326137217
Accuracy Score: -2.8530089230754627
Accuracy Score: 0.5531664837389312
Accuracy Score: 0.25621738980659214
Accuracy Score: 0.15861693720419923
Accuracy Score: -0.2325839225603763
Accuracy Score: 0.13508683036221247
Accuracy Score: -0.12574028701553086
Accuracy Score: 0.12255899240587442
Accuracy Score: -0.2852090918618031
Accuracy Score: -0.23577006433224157
Accuracy Score: -0.06496587694975875
Accuracy Score: 0.3420274552760906
Accuracy Score: 0.45670070169358634
Accuracy Score: 0.5205692496907399
Accuracy Score: -3.0764774752652118
Accuracy Score: 0.24720130114980265
Accuracy Score: -0.026940714393379528
Accuracy Score: 0.4230742286940371
Accuracy Score: 0.15891789411702262
Accuracy Score: 0.6183463176777847
Accuracy Score: 0.21152650901798176
Accuracy Score: 0.107308664430524
Accuracy Score: 0.42290062564987563
Accuracy Score: 0.0962483271363147
Accuracy Score: 0.18798660271322476
Accuracy Score: 0.1411162612563741
Accuracy Score: 0.36149452986939223
Accuracy Score: -0.08753750934057325
Accuracy Score: 0.07216118771685032
Accuracy Score: -0.1601585147668536
Accuracy Score: 0.46202837131335217

In [8]:
# rename columns for merging
temp.columns = ['SUBURB', 'r2 Score']
temp.head()

          SUBURB  r2 Score
0        Floreat  0.567241
1     City Beach  0.359261
2       Dalkeith  0.474599
3    Mosman Park  0.529051
4  Watermans Bay  0.556062

In [9]:
combined_df.head(2)

,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,NEAREST_STN,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK,Prediction
35 Oakdale Street,Floreat,2440000,6,4,2,809,442,2009,6800,Loch Street Station,3500,2018-01-08,6014,-31.94060,115.78772,NEWMAN COLLEGE,1.936173,44.0,2.236837e+06
127 Grovedale Road,Floreat,2325000,4,2,2,709,382,2013,6100,Karrakatta Station,3000,2020-01-02,6014,-31.94122,115.79516,NEWMAN COLLEGE,2.135921,44.0,1.688877e+06

In [10]:
# merge r2 Score onto recombined dataframe
sales_df_r2 = pd.merge(combined_df.reset_index(), temp, how='left', on=['SUBURB', 'SUBURB']).set_index('index')
sales_df_r2.head(2)

,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,NEAREST_STN,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK,Prediction,r2 Score
index,,,,,,,,,,,,,,,,,,,,
35 Oakdale Street,Floreat,2440000,6,4,2,809,442,2009,6800,Loch Street Station,3500,2018-01-08,6014,-31.94060,115.78772,NEWMAN COLLEGE,1.936173,44.0,2.236837e+06,0.567241
127 Grovedale Road,Floreat,2325000,4,2,2,709,382,2013,6100,Karrakatta Station,3000,2020-01-02,6014,-31.94122,115.79516,NEWMAN COLLEGE,2.135921,44.0,1.688877e+06,0.567241

In [11]:
# remove nan's of r2 scores that didn't have enough data to calculate
sales_df_r2['r2 Score'] = sales_df_r2['r2 Score'].fillna(0)

In [12]:
sales_df_r2.head()

,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,NEAREST_STN,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK,Prediction,r2 Score
index,,,,,,,,,,,,,,,,,,,,
35 Oakdale Street,Floreat,2440000,6,4,2,809,442,2009,6800,Loch Street Station,3500,2018-01-08,6014,-31.940600,115.787720,NEWMAN COLLEGE,1.936173,44.0,2.236837e+06,0.567241
127 Grovedale Road,Floreat,2325000,4,2,2,709,382,2013,6100,Karrakatta Station,3000,2020-01-02,6014,-31.941220,115.795160,NEWMAN COLLEGE,2.135921,44.0,1.688877e+06,0.567241
11 Kilkenny Road,Floreat,2300000,4,3,4,809,292,1980,7000,Loch Street Station,4100,2020-01-12,6014,-31.934491,115.787759,NEWMAN COLLEGE,1.256936,44.0,1.707688e+06,0.567241
11 Shannon Street,Floreat,2200000,3,2,2,809,266,2005,7300,Loch Street Station,4000,2020-01-10,6014,-31.936180,115.783780,NEWMAN COLLEGE,1.483140,44.0,1.584590e+06,0.567241
58 Oceanic Drive,Floreat,2200000,5,4,4,809,100,1956,7300,Loch Street Station,3800,2018-01-02,6014,-31.937999,115.783754,NEWMAN COLLEGE,1.681339,44.0,1.635198e+06,0.567241

In [13]:
# write csv to file
sales_df_r2.to_csv('Perth Housing Predictions and r2.csv', sep=',')

In [15]:
temp.to_csv('suburb_r2_scores.csv', sep=',')