In [83]:
import pandas as pd 
import numpy as np
house_sales = "Resources/Perth_Housing_Prices.csv"
sales_df = pd.read_csv(house_sales)
sales_df.set_index('ADDRESS', inplace=True)
sales_df.head()

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [84]:
sales_df['GARAGE'] = sales_df['GARAGE'].fillna(0)

In [85]:
sales_df['SUBURB'].value_counts()

Bertram            231
Iluka              212
Bennett Springs    211
Mindarie           209
Carramar           208
                  ...
Northbridge         11
Keysbrook            9
O'Connor             8
Neerabup             8
Hope Valley          6
Name: SUBURB, Length: 314, dtype: int64

In [86]:
sales_df.columns

Index(['SUBURB', 'PRICE', 'BEDROOMS', 'BATHROOMS', 'GARAGE', 'LAND_AREA',
       'FLOOR_AREA', 'BUILD_YEAR', 'CBD_DIST', 'NEAREST_STN',
       'NEAREST_STN_DIST', 'DATE_SOLD', 'POSTCODE', 'LATITUDE', 'LONGITUDE',
       'NEAREST_SCH', 'NEAREST_SCH_DIST', 'NEAREST_SCH_RANK'],
      dtype='object')

In [87]:
# column names for recombining dataframe
columns = ['SUBURB', 'PRICE', 'BEDROOMS', 'BATHROOMS', 'GARAGE', 'LAND_AREA',
       'FLOOR_AREA', 'BUILD_YEAR', 'CBD_DIST', 'NEAREST_STN',
       'NEAREST_STN_DIST', 'DATE_SOLD', 'POSTCODE', 'LATITUDE', 'LONGITUDE',
       'NEAREST_SCH', 'NEAREST_SCH_DIST', 'NEAREST_SCH_RANK', 'Prediction']

In [88]:
# create empty dataframe for recombining into
combined_df = pd.DataFrame(columns=columns)
combined_df

Empty DataFrame
Columns: [SUBURB, PRICE, BEDROOMS, BATHROOMS, GARAGE, LAND_AREA, FLOOR_AREA, BUILD_YEAR, CBD_DIST, NEAREST_STN, NEAREST_STN_DIST, DATE_SOLD, POSTCODE, LATITUDE, LONGITUDE, NEAREST_SCH, NEAREST_SCH_DIST, NEAREST_SCH_RANK, Prediction]
Index: []

In [89]:
pred_house_sell = {}
temp = {}

# loop on every suburb
for SUBURB in sales_df['SUBURB'].unique():
    # slice
    sales_slice = sales_df[sales_df['SUBURB'] == SUBURB]
    df = sales_slice.copy()

    # set X and y
    y = sales_slice['PRICE']
    X = sales_slice.drop(['SUBURB', 'PRICE', 'NEAREST_STN', 'DATE_SOLD', 'POSTCODE', 'LATITUDE', 'LONGITUDE', 'NEAREST_SCH', 'NEAREST_SCH_RANK', 'BUILD_YEAR', 'CBD_DIST', 'NEAREST_STN_DIST', 'NEAREST_SCH_DIST'], axis=1)
    
    # scale the data
    X_scaled = StandardScaler().fit_transform(X)

    # train, test, split
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y)

    #building linear regression model on training data
    model1= LinearRegression().fit(X_train, y_train)
    pred_house_sell[SUBURB] = model1.predict(X_test)
    
    # make prediction and add it to the sliced dataframe
    prediction = model1.predict(X_scaled)
    df['Prediction'] = prediction
   
    # rebuild full dataframe
    combined_df = pd.concat([combined_df, df], ignore_index=False)

    # print r2 score
    print('Accuracy Score:', r2_score(y_test, pred_house_sell[SUBURB]))  

    # build dictionary with all r2 scores
    temp[SUBURB] = r2_score(y_test, pred_house_sell[SUBURB])

# convert dictionary to dataframe
temp = pd.DataFrame.from_dict(temp, orient ='index').reset_index()

Accuracy Score: 0.5934606601206013
Accuracy Score: 0.23613575569252243
Accuracy Score: 0.25065497954174676
Accuracy Score: 0.5665876532162732
Accuracy Score: 0.3411938839602784
Accuracy Score: 0.48751268813871584
Accuracy Score: -3.3054119132414934
Accuracy Score: 0.4065595469851466
Accuracy Score: 0.47255755476602945
Accuracy Score: 0.2942810238413356
Accuracy Score: 0.5414612342846554
Accuracy Score: 0.6868752773108918
Accuracy Score: 0.3998586347182962
Accuracy Score: 0.18127648162769572
Accuracy Score: 0.4949101660105927
Accuracy Score: -0.2287978722810331
Accuracy Score: -0.04138171459372697
Accuracy Score: 0.26149174430787236
Accuracy Score: -0.25443169437044166
Accuracy Score: 0.4183411134377196
Accuracy Score: 0.4945200028164749
Accuracy Score: 0.520745448873193
Accuracy Score: 0.5832857846167994
Accuracy Score: 0.840843986664902
Accuracy Score: 0.28686500388427305
Accuracy Score: 0.4340432910883729
Accuracy Score: 0.7330713455254387
Accuracy Score: -1504.1254863673587
Accuracy Score: 0.02776867328126076
Accuracy Score: 0.46185946398870203
Accuracy Score: 0.6542368052153994
Accuracy Score: 0.35950620171653924
Accuracy Score: 0.624973673581372
Accuracy Score: 0.43381107708039857
Accuracy Score: 0.5811413063374088
Accuracy Score: 0.3615677601490247
Accuracy Score: 0.3687456640997202
Accuracy Score: 0.1766277946156215
Accuracy Score: 0.34416265134369894
Accuracy Score: -28.684219753063594
Accuracy Score: 0.13316561551469108
Accuracy Score: 0.580181697664059
Accuracy Score: 0.42529032679623413
Accuracy Score: 0.7155703936461202
Accuracy Score: -0.08236912832625176
Accuracy Score: 0.019322324366426336
Accuracy Score: 0.2665221236123517
Accuracy Score: 0.3536415352170771
Accuracy Score: -14.864190304366641
Accuracy Score: 0.07549533044989476
Accuracy Score: 0.34327161256988914
Accuracy Score: 0.3233090820618658
Accuracy Score: -0.12826898191971225
Accuracy Score: 0.6997255840858381
Accuracy Score: 0.3757382023849316
Accuracy Score: 0.17025064621013153
Accuracy Score: -12.110794420888912
Accuracy Score: -0.2201433490793554
Accuracy Score: 0.40000095614455244
Accuracy Score: 0.8417125700315283
Accuracy Score: 0.27490038776357917
Accuracy Score: -3.0880638305077666
Accuracy Score: 0.534858492938325
Accuracy Score: 0.7558136375827763
Accuracy Score: -1.0900722778161125
Accuracy Score: 0.7544115084941994
Accuracy Score: 0.6000600218208347
Accuracy Score: 0.5662410655754104
Accuracy Score: -0.05124781047093108
Accuracy Score: 0.28470712803860865
Accuracy Score: -0.498431696046465
Accuracy Score: 0.7044342606840798
Accuracy Score: -0.745108336993473
Accuracy Score: 0.31388533183499545
Accuracy Score: -0.26194759182088534
Accuracy Score: 0.3165667292509786
Accuracy Score: -0.6029947001241844
Accuracy Score: 0.4482548409899031
Accuracy Score: 0.1658699300516201
Accuracy Score: 0.04754099903482123
Accuracy Score: 0.6383960850908346
Accuracy Score: -0.16427886688524485
Accuracy Score: -0.3524169909348007
Accuracy Score: -0.294137383003946
Accuracy Score: 0.460029670229376
Accuracy Score: -0.02882547708404193
Accuracy Score: 0.33592904468737317
Accuracy Score: -0.23130089839867374
Accuracy Score: 0.7332880601527566
Accuracy Score: -0.055389273050753474
Accuracy Score: 0.06940049573574447
Accuracy Score: 0.5038832834439284
Accuracy Score: -0.7630183404021651
Accuracy Score: 0.46685088186205603
Accuracy Score: 0.1429921864694833
Accuracy Score: 0.44880690421275904
Accuracy Score: 0.1668996590941244
Accuracy Score: 0.8208066456973633
Accuracy Score: 0.4631151072574968
Accuracy Score: 0.03680952515499181
Accuracy Score: 0.7293322791645636
Accuracy Score: 0.4469873292386958
Accuracy Score: 0.6552717505775769
Accuracy Score: 0.22986220163851767
Accuracy Score: 0.4860635251454781
Accuracy Score: 0.7492545542328644
Accuracy Score: 0.6577606205754116
Accuracy Score: 0.7161703603694503
Accuracy Score: 0.8192876983592692
Accuracy Score: 0.22631718771173592
Accuracy Score: -0.28336338443332987
Accuracy Score: 0.6689266172022557
Accuracy Score: -0.6037534027999032
Accuracy Score: -0.08211907226302184
Accuracy Score: 0.6366789157242589
Accuracy Score: -0.17545729507432783
Accuracy Score: 0.7130367804696098
Accuracy Score: 0.44445529287637886
Accuracy Score: 0.2504797043490168
Accuracy Score: 0.4622902558638341
Accuracy Score: 0.6630627001066978
Accuracy Score: 0.42714511988087356
Accuracy Score: 0.18472404183300317
Accuracy Score: 0.5174147267134468
Accuracy Score: 0.06416445777242674
Accuracy Score: 0.6763077080076633
Accuracy Score: 0.2370790337980273
Accuracy Score: 0.5181481426165297
Accuracy Score: 0.5757273954459343
Accuracy Score: -0.6952145485644898
Accuracy Score: 0.4416669112466176
Accuracy Score: 0.005199549353242516
Accuracy Score: 0.6640580075278635
Accuracy Score: 0.5949314255751011
Accuracy Score: -0.5099985170662971
Accuracy Score: 0.2901016255578157
Accuracy Score: 0.15117155082058542
Accuracy Score: 0.48885305667626067
Accuracy Score: 0.300239780089975
Accuracy Score: 0.7738174017726265
Accuracy Score: 0.29452944095036604
Accuracy Score: 0.5322528004472862
Accuracy Score: -0.231432135004771
Accuracy Score: 0.46091723197067636
Accuracy Score: 0.5609427291415274
Accuracy Score: 0.7422898767503097
Accuracy Score: 0.7467885823889804
Accuracy Score: 0.4186078452625782
Accuracy Score: 0.45955318461379624
Accuracy Score: 0.5862141203484587
Accuracy Score: 0.42387740721160005
Accuracy Score: 0.5095250253602679
Accuracy Score: -0.2572867759989368
Accuracy Score: -2.6474057658490424
Accuracy Score: -1.9326115591119
Accuracy Score: 0.3762211822459579
Accuracy Score: -1.3958589036252427
Accuracy Score: 0.42587121980595954
Accuracy Score: 0.7708267589954148
Accuracy Score: 0.7497923384130745
Accuracy Score: 0.29457906652744137
Accuracy Score: -0.37435991210523656
Accuracy Score: 0.22158633098434966
Accuracy Score: 0.6507965781383915
Accuracy Score: 0.4559069594606153
Accuracy Score: 0.4032421394266269
Accuracy Score: 0.6162660744185764
Accuracy Score: 0.32671715450410843
Accuracy Score: 0.5988449112446361
Accuracy Score: 0.5268353261784727
Accuracy Score: -0.31218790204070435
Accuracy Score: -0.5819994567233675
Accuracy Score: 0.3320231434052512
Accuracy Score: 0.554898972121315
Accuracy Score: 0.581704716817844
Accuracy Score: -0.7185546603174393
Accuracy Score: -0.09266465154538395
Accuracy Score: 0.6017540961161554
Accuracy Score: 0.19245345102343148
Accuracy Score: 0.5100906256819799
Accuracy Score: 0.4119752024197939
Accuracy Score: 0.6752296179278128
Accuracy Score: 0.04588330140322949
Accuracy Score: 0.791011917363468
Accuracy Score: -1.262434034781652
Accuracy Score: -0.31043639721954897
Accuracy Score: 0.011055546414284079
Accuracy Score: 0.5129062069790199
Accuracy Score: 0.14346171746911096
Accuracy Score: 0.42966557699909824
Accuracy Score: -0.027586633196704735
Accuracy Score: 0.5893579261924557
Accuracy Score: -0.12016636290774096
Accuracy Score: 0.5797556374867071
Accuracy Score: -17.785696766467417
Accuracy Score: 0.7076079644739894
Accuracy Score: 0.7822542660203514
Accuracy Score: 0.5904703669183229
Accuracy Score: 0.6450421604579114
Accuracy Score: 0.640637790160631
Accuracy Score: 0.0345122454789587
Accuracy Score: 0.6713525446692319
Accuracy Score: 0.5090393865136269
Accuracy Score: 0.7015092465022774
Accuracy Score: -0.053740016571031335
Accuracy Score: 0.44419976787176496
Accuracy Score: 0.5976010338846159
Accuracy Score: 0.4511666518261791
Accuracy Score: 0.8132167086875264
Accuracy Score: 0.28174201788201825
Accuracy Score: 0.7699931073655313
Accuracy Score: 0.5318912878870987
Accuracy Score: 0.4693236426655363
Accuracy Score: 0.2138039750138342
Accuracy Score: 0.3526226103123351
Accuracy Score: 0.10732080747815509
Accuracy Score: 0.2864549412075893
Accuracy Score: -170.00893199850321
Accuracy Score: 0.7265557699397651
Accuracy Score: 0.6972382391577588
Accuracy Score: 0.5910511640469698
Accuracy Score: -0.21044308333727058
Accuracy Score: -113.10529694909317
Accuracy Score: 0.5931354671721397
Accuracy Score: 0.47349420553903654
Accuracy Score: 0.3277750397223551
Accuracy Score: 0.6434460211892741
Accuracy Score: 0.5134329740659238
Accuracy Score: 0.5137346971392174
Accuracy Score: 0.08211406953895573
Accuracy Score: 0.40464823945862893
Accuracy Score: 0.37336128065126917
Accuracy Score: 0.5294571056482188
Accuracy Score: 0.3258833519087043
Accuracy Score: -12.112553483223678
Accuracy Score: 0.7769213387853786
Accuracy Score: 0.5524842551988352
Accuracy Score: 0.7975963159816745
Accuracy Score: 0.6250299215905053
Accuracy Score: 0.8554282183812058
Accuracy Score: 0.29984331558925836
Accuracy Score: 0.5047784145230038
Accuracy Score: 0.004140809456753769
Accuracy Score: 0.4810141398411246
Accuracy Score: 0.7443223938562313
Accuracy Score: 0.4424763670742925
Accuracy Score: 0.6310918588546682
Accuracy Score: -0.2768169849918414
Accuracy Score: 0.17202609077584718
Accuracy Score: -0.218533125708408
Accuracy Score: 0.37071824917699425
Accuracy Score: 0.695032487793271
Accuracy Score: 0.3562756261285992
Accuracy Score: 0.4975009076835504
Accuracy Score: 0.4796053085138021
Accuracy Score: 0.4315384001807253
Accuracy Score: 0.05806210083341001
Accuracy Score: -0.7300429223346068
Accuracy Score: 0.7019975541396646
Accuracy Score: 0.18933347573203696
Accuracy Score: 0.12788570953413092
Accuracy Score: 0.28480191659743614
Accuracy Score: 0.20300945933508152
Accuracy Score: 0.47293893532398024
Accuracy Score: -0.16982268121291044
Accuracy Score: 0.3905364427103437
Accuracy Score: 0.30281762489141817
Accuracy Score: 0.6414820926093644
Accuracy Score: 0.16853819513986068
Accuracy Score: 0.1399577909067835
Accuracy Score: 0.2421365354735927
Accuracy Score: 0.11621679331938983
Accuracy Score: 0.5995718617354489
Accuracy Score: 0.49669973249987664
Accuracy Score: 0.29924573226798656
Accuracy Score: 0.3605861588344561
Accuracy Score: 0.015981750731630884
Accuracy Score: 0.3334502709997259
Accuracy Score: 0.4180329277987188
Accuracy Score: 0.08978348369796751
Accuracy Score: 0.8466130424733911
Accuracy Score: 0.7181676597655899
Accuracy Score: 0.6295847376993434
Accuracy Score: -0.35780768356727055
Accuracy Score: 0.7368443430449698
Accuracy Score: -0.013393352776763123
Accuracy Score: 0.1334275810756338
Accuracy Score: 0.20663457034542299
Accuracy Score: -578.1545439035125
Accuracy Score: 0.4435611875208063
Accuracy Score: 0.19731779004441063
Accuracy Score: -0.3346404671790397
Accuracy Score: -0.10125213033847502
Accuracy Score: 0.15201882557694846
Accuracy Score: 0.25915792497066525
Accuracy Score: 0.471030697914677
Accuracy Score: 0.5856539002494593
Accuracy Score: 0.2674104415063556
Accuracy Score: 0.25009861662392063
Accuracy Score: -0.2082774880031888
Accuracy Score: 0.42200809523686755
Accuracy Score: 0.0012064558210073129
Accuracy Score: 0.2611379876869053
Accuracy Score: -1.5385602339299322
Accuracy Score: -0.5444890375849571
Accuracy Score: 0.44012518823850166
Accuracy Score: 0.17332780479119536
Accuracy Score: 0.36999379064557436
Accuracy Score: -0.007860440194798146
Accuracy Score: 0.3948915962058027
Accuracy Score: 0.1701512720341254
Accuracy Score: 0.3133744956381679
Accuracy Score: 0.1324006906518218
Accuracy Score: 0.26366710554555506

In [90]:
# rename columns for merging
temp.columns = ['SUBURB', 'r2 Score']
temp.head()

          SUBURB  r2 Score
0        Floreat  0.593461
1     City Beach  0.236136
2       Dalkeith  0.250655
3    Mosman Park  0.566588
4  Watermans Bay  0.341194

In [91]:
combined_df.head(2)

,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,NEAREST_STN,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK,Prediction
35 Oakdale Street,Floreat,2440000,6,4,2,809,442,2009,6800,Loch Street Station,3500,2018-01-08,6014,-31.94060,115.78772,NEWMAN COLLEGE,1.936173,44.0,2.207074e+06
127 Grovedale Road,Floreat,2325000,4,2,2,709,382,2013,6100,Karrakatta Station,3000,2020-01-02,6014,-31.94122,115.79516,NEWMAN COLLEGE,2.135921,44.0,1.675303e+06

In [92]:
# merge r2 Score onto recombined dataframe
sales_df_r2 = pd.merge(combined_df.reset_index(), temp, how='left', on=['SUBURB', 'SUBURB']).set_index('index')
sales_df_r2.head(2)

,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,NEAREST_STN,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK,Prediction,r2 Score
index,,,,,,,,,,,,,,,,,,,,
35 Oakdale Street,Floreat,2440000,6,4,2,809,442,2009,6800,Loch Street Station,3500,2018-01-08,6014,-31.94060,115.78772,NEWMAN COLLEGE,1.936173,44.0,2.207074e+06,0.593461
127 Grovedale Road,Floreat,2325000,4,2,2,709,382,2013,6100,Karrakatta Station,3000,2020-01-02,6014,-31.94122,115.79516,NEWMAN COLLEGE,2.135921,44.0,1.675303e+06,0.593461

In [93]:
# remove nan's of r2 scores that didn't have enough data to calculate
sales_df_r2['r2 Score'] = sales_df_r2['r2 Score'].fillna(0)

In [94]:
sales_df_r2.head()

,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,NEAREST_STN,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK,Prediction,r2 Score
index,,,,,,,,,,,,,,,,,,,,
35 Oakdale Street,Floreat,2440000,6,4,2,809,442,2009,6800,Loch Street Station,3500,2018-01-08,6014,-31.940600,115.787720,NEWMAN COLLEGE,1.936173,44.0,2.207074e+06,0.593461
127 Grovedale Road,Floreat,2325000,4,2,2,709,382,2013,6100,Karrakatta Station,3000,2020-01-02,6014,-31.941220,115.795160,NEWMAN COLLEGE,2.135921,44.0,1.675303e+06,0.593461
11 Kilkenny Road,Floreat,2300000,4,3,4,809,292,1980,7000,Loch Street Station,4100,2020-01-12,6014,-31.934491,115.787759,NEWMAN COLLEGE,1.256936,44.0,1.678658e+06,0.593461
11 Shannon Street,Floreat,2200000,3,2,2,809,266,2005,7300,Loch Street Station,4000,2020-01-10,6014,-31.936180,115.783780,NEWMAN COLLEGE,1.483140,44.0,1.428023e+06,0.593461
58 Oceanic Drive,Floreat,2200000,5,4,4,809,100,1956,7300,Loch Street Station,3800,2018-01-02,6014,-31.937999,115.783754,NEWMAN COLLEGE,1.681339,44.0,1.515806e+06,0.593461

In [95]:
# write csv to file
sales_df_r2.to_csv('Perth Housing Predictions and r2.csv', sep=',')

In [96]:
temp.to_csv('suburb_r2_scores.csv', sep=',')